name: 'sancha1090'
version: '1.0.0'
config-version: 2

profile: 'sancha1090'

test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]

target-path: "target"

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sancha1090:
    staging:
      +materialized: table
      +schema: silver
    silver:
      +materialized: table
      +schema: silver
    marts:
      +materialized: table
      +schema: gold
