opensky:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('ANALYTICS_PG_HOST', 'postgres-analytics') }}"
      user: "{{ env_var('ANALYTICS_PG_USER', 'analytics') }}"
      password: "{{ env_var('ANALYTICS_PG_PASSWORD', 'analytics') }}"
      port: "{{ env_var('ANALYTICS_PG_PORT', '5432') | as_number }}"
      dbname: "{{ env_var('ANALYTICS_PG_DB', 'analytics') }}"
      schema: marts
      threads: 4
