opensky:
  target: trino
  outputs:
    trino:
      type: trino
      method: none
      user: root
      password: ""
      host: trino-coordinator
      port: 8080
      http_scheme: http
      catalog: iceberg
      schema: gold
      threads: 4
      session_properties:
        query_max_run_time: 5m
