networks:
  default:
    name: sancha1090_net
    driver: bridge

services:
  airflow-apiserver:
    ports:
      - "127.0.0.1:38080:8080"
  postgres-analytics:
    ports:
      - "127.0.0.1:35432:5432"
  superset:
    ports:
      - "127.0.0.1:38088:8088"
  trino-coordinator:
    ports:
      - "127.0.0.1:38090:8080"
  risingwave:
    ports:
      - "127.0.0.1:34566:4566"
  livemap:
    ports:
      - "127.0.0.1:38100:8000"
