slice_name: Anomaly Map
description: null
certified_by: null
certification_details: null
viz_type: deck_scatter
params:
  datasource: 1__table
  viz_type: deck_scatter
  slice_id: 12
  matrixify_enable: false
  matrixify_mode_columns: disabled
  matrixify_dimension_selection_mode_columns: members
  matrixify_dimension_columns:
    dimension: ''
    values: []
  matrixify_topn_value_columns: 10
  matrixify_all_sort_by_columns: a_to_z
  matrixify_topn_order_columns: true
  matrixify_show_column_headers: true
  matrixify_fit_columns_dynamically: true
  matrixify_mode_rows: disabled
  matrixify_dimension_selection_mode_rows: members
  matrixify_dimension_rows:
    dimension: ''
    values: []
  matrixify_topn_value_rows: 10
  matrixify_all_sort_by_rows: a_to_z
  matrixify_topn_order_rows: true
  matrixify_show_row_labels: true
  matrixify_row_height: 300
  matrixify_charts_per_row: 4
  matrixify_cell_title_template: ''
  spatial:
    type: geohash
    geohashCol: baro_altitude_m
    reverseCheckbox: false
  row_limit: 10000
  filter_nulls: true
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: snapshot_time
  tooltip_contents: []
  tooltip_template: ''
  mapbox_style: mapbox://styles/mapbox/dark-v9
  autozoom: true
  viewport:
    bearing: 0
    latitude: 31.222656842808707
    longitude: 6.85236157047845
    pitch: 0
    zoom: 1
  point_radius_fixed:
    type: fix
    value: '30000'
  point_unit: square_m
  min_radius: 2
  max_radius: 250
  multiplier: 1
  legend_position: tr
  legend_format: SMART_NUMBER
  color_scheme_type: categorical_palette
  color_picker:
    a: 1
    b: 135
    g: 122
    r: 0
  dimension: anomaly_type
  color_scheme: d3Category10
  default_breakpoint_color:
    a: 1
    b: 158
    g: 158
    r: 158
  js_columns: []
  js_data_mutator: ''
  js_tooltip: ''
  js_onclick_href: ''
  time_grain_sqla: null
  granularity: null
  extra_form_data: {}
  dashboards:
  - 2
query_context: '{"datasource":{"id":1,"type":"table"},"force":false,"queries":[{"filters":[{"col":"snapshot_time","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"baro_altitude_m","op":"IS NOT NULL","val":null}],"extras":{"time_grain_sqla":null,"having":"","where":""},"applied_time_extras":{},"columns":["baro_altitude_m","anomaly_type"],"metrics":[],"orderby":[],"annotation_layers":[],"row_limit":10000,"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"is_timeseries":false}],"form_data":{"datasource":"1__table","viz_type":"deck_scatter","slice_id":12,"matrixify_enable":false,"matrixify_mode_columns":"disabled","matrixify_dimension_selection_mode_columns":"members","matrixify_dimension_columns":{"dimension":"","values":[]},"matrixify_topn_value_columns":10,"matrixify_all_sort_by_columns":"a_to_z","matrixify_topn_order_columns":true,"matrixify_show_column_headers":true,"matrixify_fit_columns_dynamically":true,"matrixify_mode_rows":"disabled","matrixify_dimension_selection_mode_rows":"members","matrixify_dimension_rows":{"dimension":"","values":[]},"matrixify_topn_value_rows":10,"matrixify_all_sort_by_rows":"a_to_z","matrixify_topn_order_rows":true,"matrixify_show_row_labels":true,"matrixify_row_height":300,"matrixify_charts_per_row":4,"matrixify_cell_title_template":"","spatial":{"type":"geohash","geohashCol":"baro_altitude_m","reverseCheckbox":false},"row_limit":10000,"filter_nulls":true,"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"snapshot_time"}],"tooltip_contents":[],"tooltip_template":"","mapbox_style":"mapbox://styles/mapbox/dark-v9","autozoom":true,"viewport":{"bearing":0,"latitude":31.222656842808707,"longitude":6.85236157047845,"pitch":0,"zoom":1},"point_radius_fixed":{"type":"fix","value":"30000"},"point_unit":"square_m","min_radius":2,"max_radius":250,"multiplier":1,"legend_position":"tr","legend_format":"SMART_NUMBER","color_scheme_type":"categorical_palette","color_picker":{"a":1,"b":135,"g":122,"r":0},"dimension":"anomaly_type","color_scheme":"d3Category10","default_breakpoint_color":{"a":1,"b":158,"g":158,"r":158},"js_columns":[],"js_data_mutator":"","js_tooltip":"","js_onclick_href":"","time_grain_sqla":null,"granularity":null,"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fe234934-2384-4abc-ae78-056276908c34
version: 1.0.0
dataset_uuid: 089ea899-67f8-4869-bf02-a76a8281bdf0
