from __future__ import annotations

import csv
import json
import re
import sys
import urllib.request
from urllib.parse import urlparse
from pathlib import Path


# Mictronics readsb operators DB — the source tar1090/readsb/adsbexchange use; tracks current ICAO
# Doc 8585 designators, unlike the frozen OpenFlights airlines.dat (stale codes, e.g. AIH was a
# defunct "Alpine Air Chile" but ICAO reassigned it to Air Incheon).
SOURCE_URL = "https://raw.githubusercontent.com/Mictronics/readsb/master/webapp/src/db/operators.json"
SEED = Path(__file__).resolve().parent.parent / "dbt/sancha1090/seeds/dim_airlines.csv"

_DESIGNATOR = re.compile(r"[A-Z]{3}")

# Mictronics flattens Taiwan and Hong Kong carriers to "China"; restore the registering jurisdiction
# (separate CAA + reg prefix) for the ones that fly the Tokyo box. Codes verified against the source.
_TAIWAN = {"CAL", "EVA", "FEA", "MDA", "SJX", "TNA", "TTW", "UIA"}
_HONG_KONG = {"AHK", "CPA", "CRK", "HDA", "HKC", "HKE", "HKG", "HKJ", "JKT"}

# Brand/common name where Mictronics carries the verbose legal entity or a mashed-in hub city.
# Hand-curated; takes precedence over the Wikidata-derived _WIKIDATA_NAME below.
_NAME = {
    "EVA": "EVA Air",            # Eva Airways Corporation
    "CPA": "Cathay Pacific",     # Cathay Pacific Airways
    "UIA": "UNI Air",            # Uni Airways Corporation
    "TNA": "TransAsia Airways",  # Transasia Airways
    "KAL": "Korean Air",         # Korean Air Lines.
    "BOX": "AeroLogic",          # Mictronics mashes the hub city in: "Aerologicleipzig"
    "ATG": "AeroTransCargo",     # Mictronics "Aerotranscargo"; Wikidata "Aerotrans" wrongly drops cargo
    "APJ": "Peach Aviation",     # Mictronics "Peach Aviation Limited"; Wikidata "Peach" too terse
}

# Code-level upstream errors: Mictronics maps these designators to the wrong/stale operator entirely
# (not just a messy name). Full-row corrections, verified against ICAO Doc 8585 / the live carrier.
_FIX = {
    "RAC": {"name": "Ryukyu Air Commuter", "callsign": "RYUKYU", "country": "Japan"},  # Mictronics: Icar Air / Bosnia (wrong)
}

assert not (_NAME.keys() & _FIX.keys()), f"overlapping designators in _NAME and _FIX: {_NAME.keys() & _FIX.keys()}"


# Wikidata-derived clean names (P230 ICAO designator -> English label), baked static from a one-shot
# cross-reference reviewed 2026-06-17. Mictronics stays the authority for code->operator; Wikidata only
# beautifies the name when its label confirms (prefix-matches) the Mictronics name. Regenerate via
# scripts/propose_airline_name_overrides.py (dev-only; NOT a build/runtime dependency).
_WIKIDATA_NAME = {
    'AAZ': 'Aeolus Air',
    'ABG': 'Royal Flight',
    'ABP': 'ABS Jets',
    'ABQ': 'airblue',
    'ABW': 'AirBridgeCargo Airlines',
    'ABX': 'ABX Air',
    'ACL': 'AerCaribe',
    'ACP': 'Astral Aviation',
    'ACV': 'Air Carnival',
    'ADN': 'Aero-Dienst',
    'ADO': 'Air Do',
    'AEH': 'Aero4M',
    'AFL': 'Aeroflot',
    'AGB': 'Air Service Gabon',
    'AGU': 'Angara Airlines',
    'AHU': 'ABC Air Hungary',
    'AIC': 'Air India',
    'AIQ': 'Thai AirAsia',
    'AIZ': 'Arkia',
    'AJA': 'Afghan Jet International',
    'AJK': 'Allied Air',
    'AKL': 'Air Kiribati',
    'AKX': 'ANA Wings',
    'AKY': 'Yak-Service',
    'ALK': 'SriLankan Airlines',
    'ALV': 'Aeropostal Alas de Venezuela',
    'AMW': 'Armenia Airways',
    'AMY': 'Air Mandalay',
    'ANE': 'Air Nostrum',
    'ANP': 'Air Nigeria',
    'ANR': 'Yanair',
    'ANT': 'Air North',
    'AOJ': 'Avcon Jet',
    'APF': 'Amapola Flyg',
    'APG': 'Philippines AirAsia',
    'APK': 'Air Peace',
    'AQU': 'AirQuarius Aviation',
    'ASB': 'Air Spray',
    'ASP': 'AirSprint',
    'ASQ': 'ExpressJet',
    'ATL': 'Atlas Air Service',
    'ATM': 'Airlines of Tasmania',
    'ATR': 'Atrak Air',
    'ATV': 'Avanti Air',
    'ATX': 'AirSWIFT',
    'AUK': 'Auric Air',
    'AUL': 'Nordavia',
    'AWG': 'Animawings',
    'AWI': 'Air Wisconsin',
    'AWK': 'Airwork',
    'AWQ': 'Indonesia AirAsia',
    'AWS': 'Arab Wings',
    'AWU': 'Sylt Air',
    'AWZ': 'Air West',
    'AXC': 'Indochina Airlines',
    'AXM': 'AirAsia',
    'AXY': 'AirX Charter',
    'AYY': 'Air Alliance Express',
    'AZA': 'Alitalia',
    'AZB': 'Zambia Airways',
    'AZE': 'Arcus Air',
    'AZF': 'Air Zermatt',
    'AZM': 'Azman Air',
    'BBG': 'Bluebird Airways',
    'BBW': 'BB Airways',
    'BBZ': 'Bluebird Aviation',
    'BCS': 'European Air Transport',
    'BCY': 'CityJet',
    'BFD': 'Bertelsmann',
    'BGH': 'BH Air',
    'BHL': 'Bristow Helicopters',
    'BHO': 'Bhoja Air',
    'BHZ': 'BHS Aviation',
    'BLA': 'Blue Air',
    'BLV': 'Bellview Airlines',
    'BLX': 'TUIfly Nordic',
    'BON': 'B&H Airlines',
    'BOS': 'OpenSkies',
    'BTI': 'AirBaltic',
    'BTK': 'Batik Air',
    'BTR': 'Botir-Avia',
    'BUR': 'Air Bucharest',
    'BVR': 'ACM Air Charter',
    'BVT': 'Berjaya Air',
    'BXH': 'Bar XH Air',
    'CAT': 'Copenhagen Air Taxi',
    'CAZ': 'Cat Aviation',
    'CDN': 'Canadian Helicopters',
    'CEB': 'Cebu Pacific',
    'CEL': 'CEIBA Intercontinental',
    'CFE': 'BA CityFlyer',
    'CFH': 'CareFlight',
    'CHH': 'Hainan Airlines',
    'CIG': 'Sirius-Aero',
    'CIR': 'Arctic Circle Air',
    'CJT': 'Cargojet',
    'CJX': 'Jiangxi Air',
    'CLH': 'Lufthansa CityLine',
    'CLU': 'CargoLogicAir',
    'CLX': 'Cargolux',
    'CMI': 'Continental Micronesia',
    'CNB': 'CityLine Hungary',
    'CNF': 'Canaryfly',
    'CNW': 'North-Western Cargo International Airlines',
    'CQN': 'Chongqing Airlines',
    'CSA': 'Czech Airlines',
    'CSB': '21 Air',
    'CSC': 'Sichuan Airlines',
    'CSQ': 'IBC Airways',
    'CSS': 'SF Airlines',
    'CSW': 'SW Italia',
    'CTV': 'Citilink',
    'CUH': 'Urumqi Air',
    'CVK': 'CAVOK Air',
    'CXS': 'Boston-Maine Airways',
    'CYL': 'Alitalia CityLiner',
    'DAE': 'DHL Aero Expreso',
    'DAN': 'Dana Air',
    'DCD': 'Air 26',
    'DCP': 'Delta Connection',
    'DCS': 'DC Aviation',
    'DCT': 'Directflight',
    'DLY': 'Air Independence',
    'DNU': 'DOT LT',
    'DRK': 'Drukair',
    'DRU': 'ALROSA Air Company',
    'DXT': 'Air Management Group',
    'EAK': 'Euro-Asia Air',
    'EAL': 'Eastern Air Lines',
    'EDW': 'Edelweiss Air',
    'EFX': 'Easy Fly Express',
    'EIN': 'Aer Lingus',
    'EJA': 'NetJets',
    'EJU': 'easyJet Europe',
    'ELO': 'EuroLOT',
    'EOK': 'Aero K',
    'ERX': 'Earth Airlines',
    'ESD': 'EastIndo',
    'ESR': 'Eastar Jet',
    'ETH': 'Ethiopian Airlines',
    'ETN': 'Chim-Nir Aviation',
    'EVJ': 'Everjets',
    'EYE': 'FS Air Service',
    'EZE': 'Eastern Airways',
    'EZS': 'EasyJet Switzerland',
    'EZX': 'Eaglexpress',
    'EZY': 'easyJet',
    'FAD': 'flyadeal',
    'FBS': 'FlyBosnia',
    'FCB': 'Cobalt Air',
    'FDB': 'flydubai',
    'FDK': 'FlyDamas',
    'FEA': 'Far Eastern Air Transport',
    'FEG': 'FlyEgypt',
    'FGD': 'Conair Group',
    'FHM': 'Freebird Airlines Europe',
    'FHY': 'Freebird Airlines',
    'FIA': 'FlyOne',
    'FJW': 'Fastjet Zimbabwe',
    'FLI': 'Atlantic Airways',
    'FLZ': 'Flightlink',
    'FNK': 'IAS Itzehoer Airservice',
    'FPO': 'ASL Airlines France',
    'FRN': 'First Nation Airways',
    'FXT': 'Flexflight',
    'FYE': 'Easy Link Aviation',
    'GAC': 'GlobeAir',
    'GBB': 'Global Aviation',
    'GBQ': 'Gambia Bird',
    'GDK': 'Goldeck-Flug',
    'GEC': 'Lufthansa Cargo',
    'GEN': 'Gensa',
    'GFM': 'Grafair',
    'GIA': 'Garuda Indonesia',
    'GJT': 'GetJet Airlines',
    'GLG': 'Avianca Ecuador',
    'GNJ': 'GainJet',
    'GSC': 'Grandstar Cargo',
    'GSW': 'Chair Airlines',
    'GWI': 'Germanwings',
    'GWR': 'Aura Airlines',
    'GWY': 'USA3000 Airlines',
    'GZP': 'Gazprom Avia',
    'HHA': 'Atlantic Airlines de Honduras',
    'HHE': 'Heli Holland',
    'HHN': 'Hahn Air',
    'HKS': 'CHC Helikopter Service',
    'HPA': 'Pearl Airways',
    'HPY': 'Happy Air',
    'HYT': 'YTO Cargo Airlines',
    'IAE': 'IrAero',
    'IBE': 'Iberia',
    'IMG': 'ImagineAir',
    'INC': 'Insel Air',
    'IOS': 'Isles of Scilly Skybus',
    'IRO': 'CSA Air',
    'IWY': 'InterCaribbean Airways',
    'IYE': 'Yemenia',
    'JAB': 'Air Bagan',
    'JAS': 'Jet Aviation',
    'JAT': 'JetSmart',
    'JBA': 'Helijet',
    'JBU': 'JetBlue Airways',
    'JEF': 'Jetflite',
    'JGO': 'JetGo Australia',
    'JIA': 'PSA Airlines',
    'JKT': 'Jetstar Hong Kong',
    'JLL': 'JetLite',
    'JLM': 'Atlantic Express',
    'JLX': 'JetLink Express',
    'JMC': 'JMC Air',
    'JMP': 'Businesswings',
    'JMX': 'Air Jamaica Express',
    'JOS': 'DHL de Guatemala',
    'JTE': 'National Jet Express',
    'JUS': 'USA Jet Airlines',
    'KAC': 'Kuwait Airways',
    'KAI': 'KaiserAir',
    'KBR': 'KoralBlue Airlines',
    'KDC': 'KD Air',
    'KEA': 'Korea Express Air',
    'KEJ': 'Kaz Air Jet',
    'KEM': 'CemAir',
    'KEN': 'Kenmore Air',
    'KFR': 'Kingfisher Airlines',
    'KLC': 'KLM Cityhopper',
    'KLM': 'KLM',
    'KMA': 'Komiaviatrans',
    'KMI': 'K-Mile Air',
    'KPA': 'Henan Airlines',
    'KUY': 'Kaz Air Trans',
    'KZH': 'Zhezkazgan Air',
    'KZU': 'ULS Airlines Cargo',
    'LAB': 'L.A.B. Flying Service',
    'LAV': 'AlbaStar',
    'LAY': 'Layang Layang Aerospace',
    'LBT': 'Nouvelair',
    'LDM': 'Laudamotion',
    'LEM': 'Aviatsa',
    'LEU': 'Lions Air',
    'LGL': 'Luxair',
    'LGW': 'Luftfahrtgesellschaft Walter',
    'LID': 'Alidaunia',
    'LIE': 'Al-Dawood Air',
    'LLM': 'Yamal Airlines',
    'LMU': 'AlMasria Universal Airlines',
    'LNQ': 'Links Air',
    'LOF': 'Trans States Airlines',
    'LOG': 'Loganair',
    'LTE': 'LTE International Airways',
    'LUK': 'LUKOIL-AVIA',
    'LVB': 'IRS Airlines',
    'LYD': 'LyddAir',
    'LYX': 'SmartLynx Airlines Malta',
    'MAE': 'Mali Air',
    'MAS': 'Malaysia Airlines',
    'MAU': 'Air Mauritius',
    'MCM': 'Heli Air Monaco',
    'MCP': 'MarcoPolo Airways',
    'MDM': 'Medavia',
    'MEA': 'Middle East Airlines - Air Liban',
    'MEV': 'Med-View Airline',
    'MHK': 'Al-Naser Airlines',
    'MHV': 'MHS Aviation',
    'MJF': 'MJET',
    'MKG': 'Air Mekong',
    'MKR': 'Lanmei Airlines',
    'MMO': 'Malta MedAir',
    'MMZ': 'EuroAtlantic Airways',
    'MNJ': 'MenaJet',
    'MOV': 'VIM Airlines',
    'MPH': 'Martinair',
    'MRK': 'MarkAir',
    'MSE': 'EgyptAir Express',
    'MSR': 'EgyptAir',
    'MSX': 'EgyptAir Cargo',
    'MTL': 'RAF-Avia',
    'MWG': 'MASwings',
    'MYI': 'MAYAir',
    'MYW': 'MyWay Airlines',
    'NAX': 'Norwegian Air Shuttle',
    'NCH': 'Chanchangi Airlines',
    'NCN': 'Nicon Airways',
    'NCP': 'Capital Airlines',
    'NCT': 'NokScoot',
    'NEP': 'MY Jet Xpress Airlines',
    'NGL': 'Max Air',
    'NHC': 'Northern HeliCopter',
    'NIG': 'Aero Contractors',
    'NOK': 'Nok Air',
    'NPT': 'West Atlantic UK',
    'NRR': 'Nature Air',
    'NRS': 'Norwegian Air UK',
    'NRX': 'Norse Air',
    'NSE': 'SATENA',
    'NUM': 'Nomad Aviation',
    'NVQ': 'NovoAir',
    'NWG': 'Airwing',
    'NWK': 'Network Aviation',
    'NYT': 'Yeti Airlines',
    'NYX': 'Nyxair',
    'OAW': 'Helvetic Airways',
    'OKA': 'Okay Airways',
    'OKJ': 'Okada Air',
    'OKS': 'Slok Air International',
    'OLA': 'Overland Airways',
    'OMS': 'SalamAir',
    'ORI': 'Orion Air',
    'OTF': 'Orange2Fly',
    'OTT': 'OTT Airlines',
    'PAA': 'Pan American Airways',
    'PAC': 'Polar Air Cargo',
    'PAL': 'Philippine Airlines',
    'PAU': 'Palau Airways',
    'PBD': 'Pobeda',
    'PBU': 'Air Burundi',
    'PFY': 'Pel-Air',
    'PHA': 'Phoenix Air',
    'PHE': 'Pawan Hans',
    'PIA': 'Pakistan International Airlines',
    'PKZ': 'Prime Aviation',
    'PLR': 'Northwestern Air',
    'PNK': 'Airpink',
    'PNX': 'AIS Airlines',
    'PRF': 'Precision Air',
    'PRI': 'Primera Air',
    'PVL': 'PAL Airlines',
    'PVU': 'Peau Vavaʻu',
    'PWF': 'Private Wings',
    'QFA': 'Qantas Airways',
    'QGA': 'Windrose Air',
    'QNK': 'Kabo Air',
    'QNZ': 'Jetconnect',
    'QTR': 'Qatar Airways',
    'QXE': 'Horizon Air',
    'RAD': 'Alada',
    'RAW': 'Regional Air',
    'REV': 'RVL Aviation',
    'RJD': 'Rotana Jet',
    'RKA': 'Polar Airlines',
    'RLI': 'Reliant Air',
    'RLT': 'Real Tonga',
    'RLU': 'RusLine',
    'RLX': 'Go2Sky',
    'RNA': 'Nepal Airlines',
    'RNX': '1time Airline',
    'RSB': 'Ruby Star',
    'RSU': 'AeroSur',
    'RSY': 'I-Fly',
    'RUK': 'Ryanair UK',
    'RVP': 'Aero VIP',
    'RWD': 'RwandAir',
    'RWG': 'C&M Airways',
    'SAI': 'Shaheen Air',
    'SAS': 'Scandinavian Airlines',
    'SAX': 'Sabah Air',
    'SBM': 'SkyBahamas',
    'SCC': 'SeaCoast Airlines',
    'SCD': 'Associated Aviation',
    'SCR': 'Silver Cloud Air',
    'SDM': 'Rossiya',
    'SEJ': 'SpiceJet',
    'SFJ': 'StarFlyer',
    'SGU': 'Sol del Paraguay',
    'SHQ': 'Shanghai Airlines Cargo',
    'SIA': 'Singapore Airlines',
    'SIF': 'AirSial',
    'SIL': 'Silver Airways',
    'SKC': 'Skymaster Airlines',
    'SLK': 'SilkAir',
    'SLQ': 'SkyLink Express',
    'SNI': 'Savanah Airlines',
    'SOL': 'Solomon Airlines',
    'SOR': 'SonAir',
    'SPM': 'Air Saint-Pierre',
    'SQH': 'SeaPort Airlines',
    'SQP': 'SkyUp',
    'SRN': 'SprintAir',
    'SRQ': 'Cebgo',
    'SRY': 'ViaAir',
    'SSF': 'Severstal Air Company',
    'STP': 'STP Airways',
    'STQ': 'Star Wings Dortmund',
    'SUA': 'Silesia Air',
    'SUS': 'Sun Air of Scandinavia',
    'SVA': 'Saudia',
    'SXD': 'SunExpress Deutschland',
    'SXN': 'SaxonAir',
    'SZN': 'Air Senegal',
    'TAN': 'ZanAir',
    'TAR': 'Tunisair',
    'TAS': 'Lotus Air',
    'TAX': 'Thai AirAsia X',
    'TAY': 'ASL Airlines Belgium',
    'TBG': 'Tropical Airways',
    'TBS': 'Timbis Air',
    'TCE': 'Trans-Colorado Airlines',
    'TFA': 'Trans-Florida Airlines',
    'TGW': 'Scoot',
    'THA': 'Thai Airways',
    'THD': 'Thai Smile',
    'TIW': 'Transcarga',
    'TJB': 'Tayaranjet',
    'TJK': 'Tajik Air',
    'TLR': 'Air Libya',
    'TLY': 'Top Fly',
    'TOM': 'TUI Airways',
    'TQN': 'Taquan Air',
    'TQQ': 'Tarco Aviation',
    'TRA': 'Transavia',
    'TRS': 'AirTran Airways',
    'TRW': 'Transwestern Airlines',
    'TRZ': 'TransMeridian Airlines',
    'TSP': 'TonleSap Airlines',
    'TUP': 'Aviastar-TU',
    'TVJ': 'Thai Vietjet Air',
    'TZP': 'ZIPAIR Tokyo',
    'UBD': 'UR Airlines',
    'UBG': 'US-Bangla Airlines',
    'UGJ': 'UG Jet',
    'UKI': 'UK International Airlines',
    'UKL': 'Ukraine Air Alliance',
    'USH': 'US Helicopter',
    'UTA': 'UTair Aviation',
    'UTP': 'Uni-Top Airlines',
    'VAS': 'ATRAN',
    'VAW': 'Fly2Sky',
    'VDR': 'Voldirect',
    'VGO': 'New Gen Airways',
    'VIL': 'VI Airlink',
    'VIS': 'Vision Air International',
    'VJT': 'VistaJet',
    'VLG': 'Vueling',
    'VLT': 'Vertical-T',
    'VPP': 'Vintage Props and Jets',
    'VSR': 'Aviostart',
    'VTM': 'Aeronaves TSM',
    'VTY': 'Air Midwest',
    'VVM': 'Viva Macau',
    'WAJ': 'AirAsia Japan',
    'WAV': "Warbelow's Air Ventures",
    'WDL': 'WDL Aviation',
    'WEN': 'WestJet Encore',
    'WHS': 'Wiking Helikopter Service',
    'WJA': 'WestJet',
    'WLB': 'Wings of Lebanon',
    'WLC': 'Welcome Air',
    'WLD': 'Wilderness Air',
    'WNR': 'Wondair',
    'WOW': 'WOW air',
    'WRT': 'Wright Airlines',
    'WUK': 'Wizz Air UK',
    'WZZ': 'Wizz Air',
    'XAK': 'Airkenya Express',
    'XLF': 'XL Airways France',
    'XLK': 'Safarilink Aviation',
    'XLS': 'ExcelAire',
    'XOJ': 'XOJET',
    'ZAK': 'Zambia Skyways',
}

assert not (_WIKIDATA_NAME.keys() & (_NAME.keys() | _FIX.keys())), "_WIKIDATA_NAME overlaps a hand-curated override"


def _clean(name: str) -> str:
    # Mictronics has SQL-escape artifacts: doubled apostrophes and trailing periods.
    return name.replace("''", "'").strip().rstrip(".").strip()


def build(text: str) -> list[dict]:
    raw = json.loads(text)
    rows = []
    for icao in sorted(raw):
        if not _DESIGNATOR.fullmatch(icao):
            continue
        e = raw[icao]
        country = e.get("c") or ""
        if icao in _TAIWAN:
            country = "Taiwan"
        elif icao in _HONG_KONG:
            country = "Hong Kong SAR of China"
        row = {
            "icao": icao,
            "iata": "",  # Mictronics carries no IATA; column kept for schema stability (unused downstream)
            "name": _NAME.get(icao) or _WIKIDATA_NAME.get(icao) or _clean(e.get("n") or ""),
            "callsign": (e.get("r") or "").strip(),
            "country": country,
            "active": "Y",  # source curates to current operators; no per-row active flag
        }
        row.update(_FIX.get(icao, {}))
        rows.append(row)
    return rows


def main() -> int:
    parsed = urlparse(SOURCE_URL)
    if parsed.scheme != "https" or parsed.netloc != "raw.githubusercontent.com":
        raise ValueError(f"unsupported source URL: {SOURCE_URL}")
    with urllib.request.urlopen(SOURCE_URL, timeout=30) as resp:  # noqa: S310 — hardcoded https const, validated above
        rows = build(resp.read().decode("utf-8"))
    SEED.parent.mkdir(parents=True, exist_ok=True)
    with SEED.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["icao", "iata", "name", "callsign", "country", "active"],
                           lineterminator="\n")
        w.writeheader()
        w.writerows(rows)
    print(f"wrote {len(rows)} airlines -> {SEED}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
